version: '3.6'

services:
  dev:
    container_name: dev
    image: 'alpine:latest'
    volumes:
      - './App/:/app'
    ports:
      - "8082:8082"
    entrypoint: "sleep 10000"

  jenkins:
    build:
      context: .
      dockerfile: "MyJenkins.Dockerfile"
    # image: 'jenkins/jenkins:2.343'
    container_name: jenkins
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins_home:/var/jenkins_home'
      - './App/:/av_folder'
    ports:
      - 8080:8080
      - 50000:50000

  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:14.7.7-ce.0'
    hostname: 'gitlab'
    ports:
      - '80:80'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

volumes:
  jenkins_home:

networks:
  default:
    external:
      name: ci_net